"""
Runtime events used by the Terminal Agent runtime kernel.

Every subsystem communicates with the runtime through these events.
The Runtime Kernel reacts to events; it never reasons.

RuntimeEvent intentionally contains two kinds of events:

1. Runtime Facts
   Generated by Planner / Executor / Runtime Pipeline.

2. Runtime Decisions
   Generated by the Critic.

The Runtime Kernel treats both uniformly through the same
RuntimeStateMachine.
"""

from typing import Final
from enum import StrEnum


class RuntimeEvent(StrEnum):
    # ------------------------------------------------------------------
    # Planning Events
    # ------------------------------------------------------------------

    PLAN_CREATED = "plan_created"
    PLAN_UPDATED = "plan_updated"
    PLAN_FAILED = "plan_failed"
    PLAN_CANCELLED = "plan_cancelled"

    # ------------------------------------------------------------------
    # Task Events
    # ------------------------------------------------------------------

    TASK_READY = "task_ready"
    TASK_STARTED = "task_started"
    TASK_COMPLETED = "task_completed"
    PLAN_EXHAUSTED = "plan_exhausted"
    TASK_BLOCKED = "task_blocked"
    TASK_FAILED = "task_failed"
    TASK_CANCELLED = "task_cancelled"

    # ------------------------------------------------------------------
    # Execution Events
    # ------------------------------------------------------------------

    EXECUTION_STARTED = "execution_started"
    EXECUTION_COMPLETED = "execution_completed"
    EXECUTION_FAILED = "execution_failed"

    # ------------------------------------------------------------------
    # Runtime Decisions (from Critic)
    # ------------------------------------------------------------------

    CONTINUE_TASK = "continue_task"
    RETRY_TASK = "retry_task"
    PLAN_UPDATE_REQUIRED = "plan_update_required"
    REPLAN_REQUIRED = "replan_required"
    GOAL_COMPLETED = "goal_completed"


_PLANNING_EVENTS: Final = {
    RuntimeEvent.PLAN_CREATED,
    RuntimeEvent.PLAN_UPDATED,
    RuntimeEvent.PLAN_FAILED,
    RuntimeEvent.PLAN_CANCELLED,
}

_TASK_EVENTS: Final = {
    RuntimeEvent.TASK_READY,
    RuntimeEvent.TASK_STARTED,
    RuntimeEvent.TASK_COMPLETED,
    RuntimeEvent.TASK_BLOCKED,
    RuntimeEvent.TASK_FAILED,
    RuntimeEvent.TASK_CANCELLED,
}

_EXECUTION_EVENTS: Final = {
    RuntimeEvent.EXECUTION_STARTED,
    RuntimeEvent.EXECUTION_COMPLETED,
    RuntimeEvent.EXECUTION_FAILED,
}

_CRITIC_EVENTS: Final = {
    RuntimeEvent.CONTINUE_TASK,
    RuntimeEvent.TASK_COMPLETED,    
    RuntimeEvent.RETRY_TASK,
    RuntimeEvent.PLAN_UPDATE_REQUIRED,
    RuntimeEvent.REPLAN_REQUIRED,
    RuntimeEvent.GOAL_COMPLETED,
}


def is_planning_event(event: RuntimeEvent) -> bool:
    return event in _PLANNING_EVENTS


def is_task_event(event: RuntimeEvent) -> bool:
    return event in _TASK_EVENTS


def is_execution_event(event: RuntimeEvent) -> bool:
    return event in _EXECUTION_EVENTS


def is_critic_event(event: RuntimeEvent) -> bool:
    return event in _CRITIC_EVENTS
