from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class TaskPlanStatus(StrEnum):
    """
    Lifecycle state of a task plan.
    """

    CREATED = "created"
    ACTIVE = "active"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TaskItemStatus(StrEnum):
    """
    Lifecycle state of an individual task.
    """

    PENDING = "pending"
    READY = "ready"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    FAILED = "failed"
    CANCELLED = "cancelled"
    
class TaskItem(BaseModel):
    """
    Represents a single objective within a Task Plan.

    A TaskItem describes *what* should be accomplished, not *how* it
    should be executed.
    """

    task_id: str = Field(
        description="Unique identifier for this task.",
    )

    objective: str = Field(
        description="Natural language description of the objective.",
    )

    status: TaskItemStatus = Field(
        default=TaskItemStatus.PENDING,
        description="Current lifecycle status of the task.",
    )

    priority: int = Field(
        default=0,
        ge=0,
        description="Relative priority within the current plan.",
    )

    dependencies: list[str] = Field(
        default_factory=list,
        description="Task IDs that must complete before this task becomes READY.",
    )

    blockers: list[str] = Field(
        default_factory=list,
        description="Reasons currently preventing this task from progressing.",
    )

    success_criteria: list[str] = Field(
        default_factory=list,
        description="Conditions that indicate this objective has been completed.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Planner/runtime metadata associated with the task.",
    )

class TaskPlan(BaseModel):
    """
    Represents the current rolling task plan for accomplishing a goal.

    The plan contains objectives generated by the planner. Runtime
    progression and state transitions are managed by the PlanManager.
    """

    plan_id: str = Field(
        description="Unique identifier for the task plan.",
    )

    goal: str = Field(
        description="The original user goal this plan is trying to accomplish.",
    )

    status: TaskPlanStatus = Field(
        default=TaskPlanStatus.CREATED,
        description="Current lifecycle status of the task plan.",
    )

    tasks: list[TaskItem] = Field(
        default_factory=list,
        description="Ordered list of task items in the current rolling plan.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Planner/runtime metadata associated with the plan.",
    )